version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
  build:
    commands:
      - npm run build
      
artifacts:
  files:
    - build/**/*
    - node_modules/express/**/*
    - serve.js
    - application_start.sh
    - before_install.sh